# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Ars Scientia
email:       'infoarsscientia@gmail.com'
description: 
  en: 'We are a graphics design company specialized in scientific and technical content.'
  es: 'Somos una compañia de diseño gráfico especializada en contenido científico y técnico'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         '' # The base hostname & protocol for your site
#twitter:     ''
github:      'https://github.com/ArsScientia'
instagram:   'https://www.instagram.com/p/CS9lhwbruFB/?utm_source=ig_web_button_share_sheet'
facebook:    'https://www.facebook.com/ars.scientia.7549'

markdown:  kramdown
permalink: pretty
paginate:  5

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-polyglot

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - docs/

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Polyglot config
languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["js", "images", "admin"]
parallel_localization: true

